In [2]:
#Passos importantes (Análise Preditiva)

#identificar as chaves(id ou outra coluna chave)
#identificar as features categóricas e numéricas
#identificar valores que por venturam seja(null ou trucados)

#Valores nullos ou truck - Troque por valores médios
#na modelagem de dados - uso indicado (Modelagem em árvore ou )
#https://www.analyticsvidhya.com/blog/2016/04/complete-tutorial-tree-based-modeling-scratch-in-python/
#https://www.analyticsvidhya.com/blog/2015/09/complete-guide-boosting-methods/
#Lib importante - https://scikit-learn.org/stable/
#pip install sklearn ou pip install scikit

In [10]:
#libs importantes
import os
import sys
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
import random
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import make_classification

In [16]:
dataset=pd.read_csv('C:/Users/Diego/Desktop/pythonRead/train.csv')
datatest=pd.read_csv('C:/Users/Diego/Desktop/pythonRead/train - Copia.csv')
dataset['Type'] = 'treino' #Flag Treino 
datatest['Type'] = 'teste' #Flag Teste (o treino mas uma cópia de comparação)
fullData = pd.concat([dataset,datatest],axis = 0)

fullData.columns
fullData.head(10)
fullData.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,1782.000000,1782.000000,1782.000000,1428.000000,1782.000000,1782.000000,1782.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.281582,0.486456,0.835836,14.521407,1.102434,0.805831,49.679476
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.250000,0.000000,2.000000,20.000000,0.000000,0.000000,7.903100
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.750000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200